CREATE TABLE IF NOT EXISTS ideal_study_plan (
    id SERIAL PRIMARY KEY,
    lva_name VARCHAR(100) NOT NULL,
    ects NUMERIC(4, 2) NOT NULL,
    semester_num INTEGER NOT NULL,
    semester_type VARCHAR(2) NOT NULL,
    study_mode VARCHAR(10) NOT NULL
        CHECK (study_mode IN ('Vollzeit', 'Teilzeit')),
    study_start_mode VARCHAR(10) NOT NULL
        CHECK (study_start_mode IN ('Start_WS', 'Start_SS'))
);

-- Vollzeit, Beginn im Wintersemester (Start_WS, Vollzeit)
INSERT INTO ideal_study_plan (lva_name, ects, semester_num, semester_type, study_mode, study_start_mode) VALUES
('Einführung in die Wirtschaftsinformatik', 6.00, 1, 'WS', 'Vollzeit', 'Start_WS'),
('Grundlagen BWL und des integrierten Managements', 6.00, 1, 'WS', 'Vollzeit', 'Start_WS'),
('VL Einführung in die Informatik', 3.00, 1, 'WS', 'Vollzeit', 'Start_WS'),
('Einführung in die Softwareentwicklung', 6.00, 1, 'WS', 'Vollzeit', 'Start_WS'),
('Mathematik und Logik', 6.00, 1, 'WS', 'Vollzeit', 'Start_WS'),
('KS Kommunikative Fertigkeiten Englisch (B2)', 3.00, 1, 'WS', 'Vollzeit', 'Start_WS'),
('Algorithmen und Datenstrukturen', 6.00, 2, 'SS', 'Vollzeit', 'Start_WS'),
('Prozess- und Kommunikationsmodellierung', 6.00, 2, 'SS', 'Vollzeit', 'Start_WS'),
('Vertiefung Softwareentwicklung', 6.00, 2, 'SS', 'Vollzeit', 'Start_WS'),
('VL Operating Systems', 3.00, 2, 'SS', 'Vollzeit', 'Start_WS'),
('Freie Studienleistungen', 3.00, 2, 'SS', 'Vollzeit', 'Start_WS'),
('Formale Grundlagen', 6.00, 2, 'SS', 'Vollzeit', 'Start_WS'),
('Freie Studienleistungen', 3.00, 3, 'WS', 'Vollzeit', 'Start_WS'),
('Leistungserstellung und -verwertung', 6.00, 3, 'WS', 'Vollzeit', 'Start_WS'),
('KV Statistik', 3.00, 3, 'WS', 'Vollzeit', 'Start_WS'),
('IT-Projekt Engineering and Management', 6.00, 3, 'WS', 'Vollzeit', 'Start_WS'),
('Software Engineering-Methoden/Konzepte', 6.00, 3, 'WS', 'Vollzeit', 'Start_WS'),
('Datenmodellierung', 6.00, 3, 'WS', 'Vollzeit', 'Start_WS'),
('Data & Knowledge Engineering-Methoden/Konzepte', 6.00, 4, 'SS', 'Vollzeit', 'Start_WS'),
('Informationsmanagement', 6.00, 4, 'SS', 'Vollzeit', 'Start_WS'),
('Software Engineering-Anwendungen', 6.00, 4, 'SS', 'Vollzeit', 'Start_WS'),
('Grundlagen des Rechts', 6.00, 4, 'SS', 'Vollzeit', 'Start_WS'),
('Unternehmensrechnung', 6.00, 4, 'SS', 'Vollzeit', 'Start_WS'),
('Freie Studienleistungen', 3.00, 5, 'WS', 'Vollzeit', 'Start_WS'),
('Data & Knowledge Engineering-Anwendungen', 6.00, 5, 'WS', 'Vollzeit', 'Start_WS'),
('IT-Projekte Wirtschaftsinformatik', 6.00, 5, 'WS', 'Vollzeit', 'Start_WS'),
('Communications Engineering-Methoden/Konzepte', 6.00, 5, 'WS', 'Vollzeit', 'Start_WS'),
('KS Einführung in IKT, Gesellschaft, Gender und Diversity', 3.00, 5, 'WS', 'Vollzeit', 'Start_WS'),
('PS Ausgew. Aspekte der WIN + SE Fachsprache Englisch', 6.00, 5, 'WS', 'Vollzeit', 'Start_WS'),
('PS Ausgew. Aspekte der WIN', 3.00, 6, 'SS', 'Vollzeit', 'Start_WS'),
('KS Soziale Auswirkungen der IT', 3.00, 6, 'SS', 'Vollzeit', 'Start_WS'),
('Spezialisierungsfach WIN (mit Bachelorarbeit)', 12.00, 6, 'SS', 'Vollzeit', 'Start_WS'),
('Communications Engineering-Anwendungen', 6.00, 6, 'SS', 'Vollzeit', 'Start_WS'),
('Wahlfach WIWI oder WIN', 6.00, 6, 'SS', 'Vollzeit', 'Start_WS');

-- Vollzeit, Beginn im Sommersemester (Start_SS, Vollzeit)
INSERT INTO ideal_study_plan (lva_name, ects, semester_num, semester_type, study_mode, study_start_mode) VALUES
('Einführung in die Wirtschaftsinformatik', 6.00, 1, 'SS', 'Vollzeit', 'Start_SS'),
('Grundlagen BWL und des integrierten Managements', 6.00, 1, 'SS', 'Vollzeit', 'Start_SS'),
('VL Operating Systems', 3.00, 1, 'SS', 'Vollzeit', 'Start_SS'),
('Einführung in die Softwareentwicklung', 6.00, 1, 'SS', 'Vollzeit', 'Start_SS'),
('Formale Grundlagen', 6.00, 1, 'SS', 'Vollzeit', 'Start_SS'),
('KS Kommunikative Fertigkeiten Englisch (B2)', 3.00, 1, 'SS', 'Vollzeit', 'Start_SS'),
('VL Einführung in die Informatik', 3.00, 2, 'WS', 'Vollzeit', 'Start_SS'),
('Mathematik und Logik', 6.00, 2, 'WS', 'Vollzeit', 'Start_SS'),
('Datenmodellierung', 6.00, 2, 'WS', 'Vollzeit', 'Start_SS'),
('Leistungserstellung und -verwertung', 3.00, 2, 'WS', 'Vollzeit', 'Start_SS'),
('KV Statistik', 3.00, 2, 'WS', 'Vollzeit', 'Start_SS'),
('Unternehmensrechnung', 6.00, 2, 'WS', 'Vollzeit', 'Start_SS'),
('Algorithmen und Datenstrukturen', 6.00, 3, 'SS', 'Vollzeit', 'Start_SS'),
('Prozess- und Kommunikationsmodellierung', 6.00, 3, 'SS', 'Vollzeit', 'Start_SS'),
('Vertiefung Softwareentwicklung', 6.00, 3, 'SS', 'Vollzeit', 'Start_SS'),
('Data & Knowledge Engineering-Methoden/Konzepte', 6.00, 3, 'SS', 'Vollzeit', 'Start_SS'),
('Grundlagen des Rechts', 6.00, 3, 'SS', 'Vollzeit', 'Start_SS'),
('Communications Engineering-Methoden/Konzepte', 6.00, 4, 'WS', 'Vollzeit', 'Start_SS'),
('KS Einführung in IKT, Gesellschaft, Gender und Diversity', 3.00, 4, 'WS', 'Vollzeit', 'Start_SS'),
('IT-Projekt Engineering and Management', 6.00, 4, 'WS', 'Vollzeit', 'Start_SS'),
('Software Engineering-Methoden/Konzepte', 6.00, 4, 'WS', 'Vollzeit', 'Start_SS'),
('Communications Engineering-Anwendungen', 6.00, 4, 'WS', 'Vollzeit', 'Start_SS'),
('Freie Studienleistungen', 3.00, 4, 'WS', 'Vollzeit', 'Start_SS'),
('Informationsmanagement', 6.00, 5, 'SS', 'Vollzeit', 'Start_SS'),
('Data & Knowledge Engineering-Anwendungen', 6.00, 5, 'SS', 'Vollzeit', 'Start_SS'),
('Software Engineering - Anwendungen', 6.00, 5, 'SS', 'Vollzeit', 'Start_SS'),
('PS Ausgew. Aspekte der WIN + SE Fachsprache Englisch', 6.00, 5, 'SS', 'Vollzeit', 'Start_SS'),
('KS Soziale Auswirkungen der IT', 3.00, 5, 'SS', 'Vollzeit', 'Start_SS'),
('Freie Studienleistungen', 3.00, 5, 'SS', 'Vollzeit', 'Start_SS'),
('Freie Studienleistungen', 3.00, 6, 'WS', 'Vollzeit', 'Start_SS'),
('Wahlfach WIWI oder WIN', 6.00, 6, 'WS', 'Vollzeit', 'Start_SS'),
('PS Ausgew. Aspekte der WIN', 3.00, 6, 'WS', 'Vollzeit', 'Start_SS'),
('IT-Projekte Wirtschaftsinformatik', 6.00, 6, 'WS', 'Vollzeit', 'Start_SS'),
('Spezialisierungsfach WIN (mit Bachelorarbeit)', 12.00, 6, 'WS', 'Vollzeit', 'Start_SS');

-- Teilzeit, Beginn im Wintersemester (Start_WS, Teilzeit)
INSERT INTO ideal_study_plan (lva_name, ects, semester_num, semester_type, study_mode, study_start_mode) VALUES
('Einführung in die Wirtschaftsinformatik', 6.00, 1, 'WS', 'Teilzeit', 'Start_WS'),
('Grundlagen BWL und des integrierten Managements', 6.00, 1, 'WS', 'Teilzeit', 'Start_WS'),
('VL Einführung in die Informatik', 3.00, 1, 'WS', 'Teilzeit', 'Start_WS'),
('Einführung in die Softwareentwicklung', 6.00, 1, 'WS', 'Teilzeit', 'Start_WS'),
('Algorithmen und Datenstrukturen', 6.00, 2, 'SS', 'Teilzeit', 'Start_WS'),
('Prozess- und Kommunikationsmodellierung', 6.00, 2, 'SS', 'Teilzeit', 'Start_WS'),
('Vertiefung Softwareentwicklung', 6.00, 2, 'SS', 'Teilzeit', 'Start_WS'),
('KS Kommunikative Fertigkeiten Englisch (B2)', 3.00, 2, 'SS', 'Teilzeit', 'Start_WS'),
('Leistungserstellung und -verwertung', 6.00, 3, 'WS', 'Teilzeit', 'Start_WS'),
('KV Statistik', 3.00, 3, 'WS', 'Teilzeit', 'Start_WS'),
('Mathematik und Logik', 6.00, 3, 'WS', 'Teilzeit', 'Start_WS'),
('Datenmodellierung', 6.00, 3, 'WS', 'Teilzeit', 'Start_WS'),
('VL Operating Systems', 3.00, 4, 'SS', 'Teilzeit', 'Start_WS'),
('Formale Grundlagen der WIN', 6.00, 4, 'SS', 'Teilzeit', 'Start_WS'),
('Freie Studienleistungen', 3.00, 4, 'SS', 'Teilzeit', 'Start_WS'),
('Grundlagen des Rechts', 6.00, 4, 'SS', 'Teilzeit', 'Start_WS'),
('KS Grundlagen der Kostenrechnung', 3.00, 4, 'SS', 'Teilzeit', 'Start_WS'),
('Freie Studienleistungen', 3.00, 5, 'WS', 'Teilzeit', 'Start_WS'),
('IT-Projekt Engineering and Management', 6.00, 5, 'WS', 'Teilzeit', 'Start_WS'),
('Software Engineering-Methoden/Konzepte', 6.00, 5, 'WS', 'Teilzeit', 'Start_WS'),
('KS Einführung in IKT, Gesellschaft, Gender und Diversity', 3.00, 5, 'WS', 'Teilzeit', 'Start_WS'),
('KS Buchhaltung nach UGB', 3.00, 5, 'WS', 'Teilzeit', 'Start_WS'),
('Informationsmanagement', 6.00, 6, 'SS', 'Teilzeit', 'Start_WS'),
('Data & Knowledge Engineering- Methoden/Konzepte', 6.00, 6, 'SS', 'Teilzeit', 'Start_WS'),
('Software Engineering - Anwendungen', 6.00, 6, 'SS', 'Teilzeit', 'Start_WS'),
('Freie Studienleistungen', 3.00, 6, 'SS', 'Teilzeit', 'Start_WS'),
('Communications Engineering-Methoden/Konzepte', 6.00, 7, 'WS', 'Teilzeit', 'Start_WS'),
('PS Ausgew. Aspekte der WIN + SE Fachsprache Englisch', 6.00, 7, 'WS', 'Teilzeit', 'Start_WS'),
('Data & Knowledge Engineering-Anwendungen', 6.00, 7, 'WS', 'Teilzeit', 'Start_WS'),
('Communications Engineering-Anwendungen', 6.00, 8, 'SS', 'Teilzeit', 'Start_WS'),
('IT-Projekte Wirtschaftsinformatik', 6.00, 8, 'SS', 'Teilzeit', 'Start_WS'),
('KS Soziale Auswirkungen der IT', 3.00, 8, 'SS', 'Teilzeit', 'Start_WS'),
('PS Ausgew. Aspekte der WIN', 3.00, 8, 'SS', 'Teilzeit', 'Start_WS'),
('Spezialisierungsfach WIN (mit Bachelorarbeit)', 12.00, 9, 'WS', 'Teilzeit', 'Start_WS'),
('Wahlfach WIWI oder WIN', 6.00, 9, 'WS', 'Teilzeit', 'Start_WS');

-- Teilzeit, Beginn im Sommersemester (Start_SS, Teilzeit)
INSERT INTO ideal_study_plan (lva_name, ects, semester_num, semester_type, study_mode, study_start_mode) VALUES
('Einführung in die Wirtschaftsinformatik', 6.00, 1, 'SS', 'Teilzeit', 'Start_SS'),
('Grundlagen BWL und des integrierten Managements', 6.00, 1, 'SS', 'Teilzeit', 'Start_SS'),
('VL Operating Systems', 3.00, 1, 'SS', 'Teilzeit', 'Start_SS'),
('Einführung in die Softwareentwicklung', 6.00, 1, 'SS', 'Teilzeit', 'Start_SS'),
('VL Einführung in die Informatik', 3.00, 2, 'WS', 'Teilzeit', 'Start_SS'),
('Mathematik und Logik', 6.00, 2, 'WS', 'Teilzeit', 'Start_SS'),
('Datenmodellierung', 6.00, 2, 'WS', 'Teilzeit', 'Start_SS'),
('Statistik', 3.00, 2, 'WS', 'Teilzeit', 'Start_SS'),
('KS Kommunikative Fertigkeiten Englisch (B2)', 3.00, 2, 'WS', 'Teilzeit', 'Start_SS'),
('KS Grundlagen der Kostenrechnung', 3.00, 3, 'SS', 'Teilzeit', 'Start_SS'),
('Vertiefung Softwareentwicklung', 6.00, 3, 'SS', 'Teilzeit', 'Start_SS'),
('Algorithmen und Datenstrukturen', 6.00, 3, 'SS', 'Teilzeit', 'Start_SS'),
('Formale Grundlagen der WIN', 6.00, 3, 'SS', 'Teilzeit', 'Start_SS'),
('KS Buchhaltung nach UGB', 3.00, 4, 'WS', 'Teilzeit', 'Start_SS'),
('IT-Projekt Engineering and Management', 6.00, 4, 'WS', 'Teilzeit', 'Start_SS'),
('Software Engineering-Methoden/Konzepte', 6.00, 4, 'WS', 'Teilzeit', 'Start_SS'),
('Leistungserstellung und -verwertung', 6.00, 4, 'WS', 'Teilzeit', 'Start_SS'),
('Informationsmanagement', 6.00, 5, 'SS', 'Teilzeit', 'Start_SS'),
('Software Engineering - Anwendungen', 6.00, 5, 'SS', 'Teilzeit', 'Start_SS'),
('KS Soziale Auswirkungen der IT', 3.00, 5, 'SS', 'Teilzeit', 'Start_SS'),
('Prozess- und Kommunikationsmodellierung', 6.00, 5, 'SS', 'Teilzeit', 'Start_SS'),
('Communications Engineering-Methoden/Konzepte', 6.00, 6, 'WS', 'Teilzeit', 'Start_SS'),
('PS Ausgew. Aspekte der WIN + SE Fachsprache Englisch', 6.00, 6, 'WS', 'Teilzeit', 'Start_SS'),
('KS Einführung in IKT, Gesellschaft, Gender und Diversity', 3.00, 6, 'WS', 'Teilzeit', 'Start_SS'),
('Freie Studienleistungen', 6.00, 6, 'WS', 'Teilzeit', 'Start_SS'),
('Communications Engineering-Anwendung', 6.00, 7, 'SS', 'Teilzeit', 'Start_SS'),
('Grundlagen des Rechts', 6.00, 7, 'SS', 'Teilzeit', 'Start_SS'),
('Data & Knowledge Engineering- Methoden/Konzepte', 6.00, 7, 'SS', 'Teilzeit', 'Start_SS'),
('Data & Knowledge Engineering-Anwendungen', 6.00, 8, 'WS', 'Teilzeit', 'Start_SS'),
('IT-Projekte Wirtschaftsinformatik', 6.00, 8, 'WS', 'Teilzeit', 'Start_SS'),
('Wahlfach WIWI oder WIN', 6.00, 8, 'WS', 'Teilzeit', 'Start_SS'),
('Spezialisierungsfach WIN (mit Bachelorarbeit)', 12.00, 9, 'SS', 'Teilzeit', 'Start_SS'),
('Freie Studienleistungen', 3.00, 9, 'SS', 'Teilzeit', 'Start_SS'),
('PS Ausgew. Aspekte der WIN', 3.00, 9, 'SS', 'Teilzeit', 'Start_SS');
